# Generated by Django 2.2 on 2019-07-08 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
        migrations.AddField(
            model_name='user',
            name='displayName',
            field=models.CharField(blank=True, max_length=150, verbose_name='表示名'),
        ),
    ]
