version: 2
updates:
- package-ecosystem: npm
  directory: "/react/kaguya"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: uikit
    versions:
    - 3.6.14
    - 3.6.15
    - 3.6.16
    - 3.6.17
    - 3.6.18
    - 3.6.19
  - dependency-name: react-redux
    versions:
    - 7.2.3
  - dependency-name: react-select
    versions:
    - 4.0.2
    - 4.1.0
    - 4.2.0
    - 4.2.1
  - dependency-name: query-string
    versions:
    - 6.14.0
    - 6.14.1
  - dependency-name: react-scripts
    versions:
    - 4.0.2
- package-ecosystem: pip
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: django
    versions:
    - 3.1.5
    - 3.1.6
    - 3.1.7
- package-ecosystem: docker
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
