version: '3.3'
services:
  django:
    build:
      context: .
    env_file: .env
    restart: always
    expose:
      - "3031"
    # depends_on:
    #   - pgweb
    command: sh run.sh
    volumes:
      - ".:/system"
      - "./static/:/static/"

  react:
    build:
      context: ./react
    restart: always
    command: yarn --cwd ./kaguya start
    environment: 
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "35729:35729"
    volumes:
      - ./react:/system

  nginx:
    restart: always
    build:
      context: ./nginx
    depends_on:
      - django
    ports:
      - "80:80"
    volumes:
      - "./nginx/:/etc/nginx/"
      - "./static/:/system/static/"
      - "./react/kaguya:/var/www/html"

  postgres:
    image: postgres
    restart: always
    expose:
      - "5432"
    volumes:
      - "dbdata/:/var/lib/postgresql/data"
    env_file: .env

  pgweb:
    restart: always
    image: donnex/pgweb
    links:
      - postgres:postgres
    ports:
      - '8080:8080'
  
volumes:
  dbdata: