version: 2
jobs:
  build:
    machine:
      image: circleci/classic:edge
    working_directory: ~/project
    steps:
      - checkout
      - run:
          name: Decode env file
          command: echo $ENV_FILE | base64 --decode > .env

      - run:
          name: Decode env file
          command: echo $ENV_FILE | base64 --decode > react/kaguya/.env

      - run:
          name: docker-compose build
          command: docker-compose build

      - run:
          name: docker-compose run react yarn --cwd ./kaguya
          command: docker-compose run react yarn --cwd ./kaguya
      
      - run:
          name: docker-compose run react yarn --cwd ./kaguya build
          command: docker-compose run react yarn --cwd ./kaguya build

      - run:
          name: docker-compose run django python manage.py check --deploy
          command: docker-compose run django python manage.py check --deploy

      - run:
          name: docker-compose up
          command: docker-compose up -d
          
      - run:
          name: docker-compose down
          command: docker-compose down
          
  deploy:
    machine:
      image: circleci/classic:edge
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints:
            - $FINGER_PRINT
      - run:
          name: Start ssh-keyscan
          command: ssh-keyscan $SSH_HOST >> ~/.ssh/known_hosts

      - run:
          name: Deploy Command
          command: ssh $SSH_USER@$SSH_HOST ./deploy.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master