# Generated by Django 2.1.7 on 2019-04-02 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='作品名')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.Collection', verbose_name='親作品名')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
            },
        ),
        migrations.CreateModel(
            name='Haikai',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstPart', models.CharField(max_length=50, verbose_name='上の句')),
                ('secondPart', models.CharField(max_length=50, verbose_name='中の句')),
                ('lastPart', models.CharField(max_length=50, verbose_name='下の句')),
                ('firstPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='上の句(かな)')),
                ('secondPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='中の句(かな)')),
                ('lastPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='下の句(かな)')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.Collection', verbose_name='所蔵作品')),
            ],
            options={
                'verbose_name': '俳諧',
                'verbose_name_plural': '俳諧',
            },
        ),
        migrations.CreateModel(
            name='Tanka',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstPart', models.CharField(max_length=50, verbose_name='初句')),
                ('secondPart', models.CharField(max_length=50, verbose_name='二句')),
                ('thirdPart', models.CharField(max_length=50, verbose_name='三句')),
                ('fourthPart', models.CharField(max_length=50, verbose_name='四句')),
                ('lastPart', models.CharField(max_length=50, verbose_name='結句')),
                ('firstPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='初句(かな)')),
                ('secondPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='二句(かな)')),
                ('thirdPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='三句(かな)')),
                ('fourthPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='四句(かな)')),
                ('lastPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='結句(かな)')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.Collection', verbose_name='所蔵作品')),
            ],
            options={
                'verbose_name': '短歌',
                'verbose_name_plural': '短歌',
            },
        ),
    ]
