# Generated by Django 2.2 on 2019-07-31 14:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import markdownx.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='作者名')),
                ('description', markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown形式で記述できます。', null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='作品名')),
                ('description', markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown形式で記述できます。', null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='childCollection', to='search.Collection', verbose_name='親作品名')),
            ],
            options={
                'verbose_name': '作品',
                'verbose_name_plural': '作品',
                'unique_together': {('name', 'parent')},
            },
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('jpnYear', models.CharField(max_length=100, unique=True, verbose_name='和暦')),
                ('adYear', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='西暦')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '和暦',
                'verbose_name_plural': '和暦',
                'unique_together': {('jpnYear', 'adYear')},
            },
        ),
        migrations.CreateModel(
            name='Tanka',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='番号')),
                ('firstPart', models.CharField(blank=True, max_length=50, null=True, verbose_name='初句')),
                ('secondPart', models.CharField(blank=True, max_length=50, null=True, verbose_name='二句')),
                ('thirdPart', models.CharField(blank=True, max_length=50, null=True, verbose_name='三句')),
                ('fourthPart', models.CharField(blank=True, max_length=50, null=True, verbose_name='四句')),
                ('lastPart', models.CharField(blank=True, max_length=50, null=True, verbose_name='結句')),
                ('firstPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='初句(かな)')),
                ('secondPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='二句(かな)')),
                ('thirdPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='三句(かな)')),
                ('fourthPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='四句(かな)')),
                ('lastPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='結句(かな)')),
                ('description', markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown形式で記述できます。', null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.Author', verbose_name='作者名')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.Collection', verbose_name='所蔵作品')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.Year', verbose_name='発表年')),
            ],
            options={
                'verbose_name': '短歌',
                'verbose_name_plural': '短歌',
                'unique_together': {('firstPart', 'secondPart', 'thirdPart', 'fourthPart', 'lastPart', 'firstPartKana', 'secondPartKana', 'thirdPartKana', 'fourthPartKana', 'lastPartKana', 'collection', 'author')},
            },
        ),
        migrations.CreateModel(
            name='Koten',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', markdownx.models.MarkdownxField(default='', help_text='Markdown形式で記述できます。', verbose_name='本文')),
                ('description', markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown形式で記述できます。', null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.Author', verbose_name='作者名')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.Collection', verbose_name='所蔵作品')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.Year', verbose_name='発表年')),
            ],
            options={
                'verbose_name': '古典',
                'verbose_name_plural': '古典',
                'unique_together': {('text', 'collection', 'author')},
            },
        ),
        migrations.CreateModel(
            name='Haikai',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('number', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='番号')),
                ('firstPart', models.CharField(blank=True, max_length=50, null=True, verbose_name='上の句')),
                ('secondPart', models.CharField(blank=True, max_length=50, null=True, verbose_name='中の句')),
                ('lastPart', models.CharField(blank=True, max_length=50, null=True, verbose_name='下の句')),
                ('firstPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='上の句(かな)')),
                ('secondPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='中の句(かな)')),
                ('lastPartKana', models.CharField(blank=True, max_length=100, null=True, verbose_name='下の句(かな)')),
                ('description', markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown形式で記述できます。', null=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.Author', verbose_name='作者名')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.Collection', verbose_name='所蔵作品')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='created_user', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='updated_user', to=settings.AUTH_USER_MODEL, verbose_name='更新者')),
                ('year', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.Year', verbose_name='発表年')),
            ],
            options={
                'verbose_name': '俳諧',
                'verbose_name_plural': '俳諧',
                'unique_together': {('firstPart', 'secondPart', 'lastPart', 'firstPartKana', 'secondPartKana', 'lastPartKana', 'collection', 'author')},
            },
        ),
    ]
