# Generated by Django 2.2 on 2019-05-15 13:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='作者名')),
            ],
            options={
                'verbose_name': '作者',
                'verbose_name_plural': '作者',
            },
        ),
        migrations.AddField(
            model_name='haikai',
            name='number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='番号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='haikai',
            name='firstPart',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='上の句'),
        ),
        migrations.AlterField(
            model_name='haikai',
            name='lastPart',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='下の句'),
        ),
        migrations.AlterField(
            model_name='haikai',
            name='secondPart',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='中の句'),
        ),
        migrations.AlterUniqueTogether(
            name='collection',
            unique_together={('name', 'parent')},
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jpnYear', models.CharField(max_length=100, unique=True, verbose_name='和暦')),
                ('adYear', models.IntegerField(blank=True, null=True, unique=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='西暦')),
            ],
            options={
                'verbose_name': '和暦',
                'verbose_name_plural': '和暦',
                'unique_together': {('jpnYear', 'adYear')},
            },
        ),
        migrations.AddField(
            model_name='haikai',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.Author', verbose_name='作者名'),
        ),
        migrations.AddField(
            model_name='haikai',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.Year', verbose_name='発表年'),
        ),
        migrations.AddField(
            model_name='tanka',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.Author', verbose_name='作者名'),
        ),
        migrations.AddField(
            model_name='tanka',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.Year', verbose_name='発表年'),
        ),
        migrations.AlterUniqueTogether(
            name='haikai',
            unique_together={('firstPart', 'secondPart', 'lastPart', 'firstPartKana', 'secondPartKana', 'lastPartKana', 'collection', 'author')},
        ),
    ]
