# Generated by Django 2.2 on 2019-05-24 13:53

from django.db import migrations, models
import django.db.models.deletion
import markdownx.models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_auto_20190515_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown形式で記述できます。', null=True, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='collection',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown形式で記述できます。', null=True, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='haikai',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown形式で記述できます。', null=True, verbose_name='説明'),
        ),
        migrations.AddField(
            model_name='tanka',
            name='description',
            field=markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown形式で記述できます。', null=True, verbose_name='説明'),
        ),
        migrations.AlterField(
            model_name='tanka',
            name='firstPart',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='初句'),
        ),
        migrations.AlterField(
            model_name='tanka',
            name='fourthPart',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='四句'),
        ),
        migrations.AlterField(
            model_name='tanka',
            name='lastPart',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='結句'),
        ),
        migrations.AlterField(
            model_name='tanka',
            name='secondPart',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='二句'),
        ),
        migrations.AlterField(
            model_name='tanka',
            name='thirdPart',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='三句'),
        ),
        migrations.AlterUniqueTogether(
            name='tanka',
            unique_together={('firstPart', 'secondPart', 'thirdPart', 'fourthPart', 'lastPart', 'firstPartKana', 'secondPartKana', 'thirdPartKana', 'fourthPartKana', 'lastPartKana', 'collection', 'author')},
        ),
        migrations.CreateModel(
            name='Koten',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', markdownx.models.MarkdownxField(default='', help_text='Markdown形式で記述できます。', verbose_name='本文')),
                ('description', markdownx.models.MarkdownxField(blank=True, default='', help_text='Markdown形式で記述できます。', null=True, verbose_name='説明')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.Author', verbose_name='作者名')),
                ('collection', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='search.Collection', verbose_name='所蔵作品')),
            ],
            options={
                'verbose_name': '古典',
                'verbose_name_plural': '古典',
                'unique_together': {('text', 'collection', 'author')},
            },
        ),
    ]
