# Generated by Django 2.2 on 2019-05-27 09:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190524_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='koten',
            name='year',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='search.Year', verbose_name='発表年'),
        ),
    ]
