# Generated by Django 2.2.4 on 2019-11-18 13:00

import django.core.validators
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0003_auto_20190731_2335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(default='', max_length=100, validators=[django.core.validators.RegexValidator(message='全角のひらがな・カタカナ・漢字で入力してください', regex='^[ぁ-んァ-ヶー一-龠]+$')], verbose_name='タイトル')),
                ('body', models.TextField(blank=True, max_length=3000, null=True, verbose_name='本文')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'お知らせ',
                'verbose_name_plural': 'お知らせ',
            },
        ),
    ]
