# Generated by Django 2.2 on 2019-07-10 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0005_auto_20190710_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subcollection', to='search.Collection', verbose_name='親作品名'),
        ),
    ]
